package ingest

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"html"
	"log/slog"
	"path"
	"regexp"
	"strings"

	"github.com/GokulMV/DocTheRepo/internal/ports"
)

// DiagramStore keeps authored architecture diagrams (store.ArchitectureStore).
type DiagramStore interface {
	UpsertDiagram(ctx context.Context, repoID, path, title, generator, html, sha string) error
	DeleteDiagrams(ctx context.Context, repoID string, paths []string) error
	KeepDiagrams(ctx context.Context, repoID string, paths []string) (int64, error)
}

// ArchitectureSync finds diagrams committed to a repository — HTML generated by archify — and keeps the
// Architecture tab's copies current: a full scan on request, and the changed files on every push.
type ArchitectureSync struct {
	Repos interface {
		Get(ctx context.Context, id string) (ports.RepoConfig, error)
	}
	Hosts func(ctx context.Context, connectorID string) (ports.CodeHost, error)
	Store DiagramStore
	Log   *slog.Logger
}

// Limits: a scan reads at most maxDiagramCandidates files, each at most maxDiagramBytes.
const (
	maxDiagramCandidates = 60
	maxDiagramBytes      = 8 << 20
)

// IsDiagramCandidate reports whether a path may hold an authored diagram: an .html file under a folder or
// with a name about architecture or diagrams (so a scan does not read every HTML file in a repository).
func IsDiagramCandidate(p string) bool {
	lp := strings.ToLower(p)
	if !strings.HasSuffix(lp, ".html") || strings.Contains(lp, "node_modules/") {
		return false
	}
	for _, w := range []string{"architecture", "archify", "diagram", "arch/", "design/"} {
		if strings.Contains(lp, w) {
			return true
		}
	}
	return false
}

var (
	generatorRE = regexp.MustCompile(`(?i)<meta\s+name=["']generator["']\s+content=["']([^"']*)["']`)
	titleRE     = regexp.MustCompile(`(?is)<title>(.*?)</title>`)
)

// parseDiagram returns the generator and title when b is an archify diagram, or ok=false.
func parseDiagram(b []byte, p string) (generator, title string, ok bool) {
	head := b
	if len(head) > 16<<10 {
		head = head[:16<<10]
	}
	m := generatorRE.FindSubmatch(head)
	if m == nil || !bytes.HasPrefix(bytes.ToLower(m[1]), []byte("archify")) {
		return "", "", false
	}
	title = strings.TrimSuffix(path.Base(p), path.Ext(p))
	if t := titleRE.FindSubmatch(head); t != nil {
		title = strings.TrimSuffix(strings.TrimSpace(html.UnescapeString(string(t[1]))), " Diagram")
	}
	return string(m[1]), title, true
}

// ScanResult reports a scan.
type ScanResult struct {
	Found     int      `json:"found"`
	Removed   int64    `json:"removed"`
	Checked   int      `json:"checked"`
	Skipped   []string `json:"skipped,omitempty"`
	CommitSHA string   `json:"commit_sha"`
}

// Scan reads the repository's tree at the tracked branch head and replaces its stored diagrams.
func (s *ArchitectureSync) Scan(ctx context.Context, repoID string) (ScanResult, error) {
	repo, err := s.Repos.Get(ctx, repoID)
	if err != nil {
		return ScanResult{}, err
	}
	host, err := s.Hosts(ctx, repo.ConnectorID)
	if err != nil {
		return ScanResult{}, err
	}
	head, err := host.BranchHead(ctx, repo.FullName, repo.Branch())
	if err != nil {
		return ScanResult{}, fmt.Errorf("branch head: %w", err)
	}
	tree, err := host.ListTree(ctx, repo.FullName, head)
	if err != nil {
		return ScanResult{}, fmt.Errorf("list tree: %w", err)
	}
	res := ScanResult{CommitSHA: head}
	found := []string{}
	for _, p := range tree {
		if !IsDiagramCandidate(p) {
			continue
		}
		if res.Checked == maxDiagramCandidates {
			res.Skipped = append(res.Skipped, p)
			continue
		}
		res.Checked++
		ok, err := s.syncFile(ctx, host, repo, p, head)
		if err != nil {
			return res, err
		}
		if ok {
			found = append(found, p)
		}
	}
	res.Found = len(found)
	if res.Removed, err = s.Store.KeepDiagrams(ctx, repo.ID, found); err != nil {
		return res, err
	}
	return res, nil
}

// syncFile stores p when it is an archify diagram (and removes a stored copy when it no longer is).
func (s *ArchitectureSync) syncFile(ctx context.Context, host ports.CodeHost, repo ports.RepoConfig, p, ref string) (bool, error) {
	b, err := host.GetFile(ctx, repo.FullName, p, ref)
	if errors.Is(err, ports.ErrNotFound) {
		return false, s.Store.DeleteDiagrams(ctx, repo.ID, []string{p})
	}
	if err != nil {
		return false, fmt.Errorf("read %s: %w", p, err)
	}
	gen, title, ok := parseDiagram(b, p)
	if !ok || len(b) > maxDiagramBytes {
		return false, s.Store.DeleteDiagrams(ctx, repo.ID, []string{p})
	}
	return true, s.Store.UpsertDiagram(ctx, repo.ID, p, title, gen, string(b), ref)
}

// OnChanges updates stored diagrams for the files a push changed (the code_push pipeline calls it). It is
// best effort: a failure is logged and never fails the push.
func (s *ArchitectureSync) OnChanges(ctx context.Context, repo ports.RepoConfig, host ports.CodeHost, head string, changed []ports.ChangedFile) {
	var removed []string
	n := 0
	for _, c := range changed {
		if c.PreviousPath != "" && c.PreviousPath != c.Path && IsDiagramCandidate(c.PreviousPath) {
			removed = append(removed, c.PreviousPath)
		}
		if !IsDiagramCandidate(c.Path) {
			continue
		}
		if c.Status == ports.FileRemoved {
			removed = append(removed, c.Path)
			continue
		}
		if n++; n > maxDiagramCandidates {
			break
		}
		if _, err := s.syncFile(ctx, host, repo, c.Path, head); err != nil {
			s.log().Warn("architecture diagram sync failed", "repo", repo.FullName, "path", c.Path, "err", err)
		}
	}
	if len(removed) > 0 {
		if err := s.Store.DeleteDiagrams(ctx, repo.ID, removed); err != nil {
			s.log().Warn("architecture diagram delete failed", "repo", repo.FullName, "err", err)
		}
	}
}

func (s *ArchitectureSync) log() *slog.Logger {
	if s.Log != nil {
		return s.Log
	}
	return slog.Default()
}
